name: shopbanhang
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

  #dependencies:
  #  sqllite: ^2.3.2
  #  path: ^1.9.0
  #  flutter:
  #    sdk: flutter
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2     # phiên bản mới nhất hiện tại
  path: ^1.9.0

  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1  # ✅ Gói trượt ảnh phải nằm ở đây


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

